# Generated by Django 3.2.4 on 2026-09-21 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='focus_label',
            field=models.CharField(blank=True, default='Focus', max_length=50),
        ),
        migrations.AddField(
            model_name='profile',
            name='focus_text',
            field=models.CharField(blank=True, help_text='Hero card focus line, for example: Generative AI · LangGraph · Python backends', max_length=255),
        ),
    ]
