# Generated by Django 3.2.4 on 2026-09-21 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_auto_20260921_1750'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('google_api_key', models.CharField(blank=True, help_text='Google Gemini API key used by the chatbot.', max_length=255, verbose_name='Gemini API key')),
                ('gemini_model', models.CharField(default='gemini-2.0-flash', help_text='Example: gemini-2.0-flash', max_length=100, verbose_name='Gemini model name')),
                ('email_host', models.CharField(default='smtp.gmail.com', max_length=255, verbose_name='SMTP host')),
                ('email_port', models.PositiveIntegerField(default=587, verbose_name='SMTP port')),
                ('email_use_tls', models.BooleanField(default=True, verbose_name='Use TLS')),
                ('email_use_ssl', models.BooleanField(default=False, verbose_name='Use SSL')),
                ('email_host_user', models.CharField(blank=True, help_text='SMTP username / from mailbox.', max_length=254, verbose_name='Email ID')),
                ('email_host_password', models.CharField(blank=True, help_text='SMTP password or Gmail app password.', max_length=255, verbose_name='Email password')),
                ('default_from_email', models.CharField(blank=True, help_text='Leave blank to use Email ID.', max_length=254, verbose_name='From email')),
                ('contact_recipient', models.CharField(blank=True, help_text='Where contact-form messages are delivered. Leave blank to use the profile email.', max_length=254, verbose_name='Contact inbox')),
            ],
            options={
                'verbose_name': 'Site setting',
                'verbose_name_plural': 'Site settings',
            },
        ),
    ]
