# Generated by Django 3.2.4 on 2026-09-21 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_sitesettings'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sitesettings',
            options={'verbose_name': 'API and email configuration', 'verbose_name_plural': 'API and email configuration'},
        ),
    ]
