# Generated by Django 3.2.4 on 2026-09-21 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_sitesettings_verbose'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='verification_attempts',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='verification_code',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='verification_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
