# Generated by Django 3.2.4 on 2026-09-21 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_contact_email_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='eyebrow_text',
            field=models.CharField(blank=True, help_text='Short line above the name, for example: Available for challenging Python & GenAI work', max_length=255),
        ),
    ]
